"""empty message

Revision ID: 59d8b36f53e0
Revises: b48811b00f44
Create Date: 2022-05-11 13:31:27.089858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59d8b36f53e0'
down_revision = 'b48811b00f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'statistics', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'statistics', 'user', ['id'], ['id'])
    # ### end Alembic commands ###
