"""update to stats

Revision ID: 779d2e6a0d85
Revises: b48811b00f44
Create Date: 2022-05-11 18:53:58.943525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '779d2e6a0d85'
down_revision = 'b48811b00f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statistics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statistics', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['id'], ['id'])

    # ### end Alembic commands ###
