"""stats table

Revision ID: c8aebcc79b28
Revises: 0cd957191a64
Create Date: 2022-05-12 12:21:08.592652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8aebcc79b28'
down_revision = '0cd957191a64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('timeTaken', sa.String(length=140), nullable=True),
    sa.Column('game_completed', sa.DateTime(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statistics_score'), 'statistics', ['score'], unique=False)
    op.create_index(op.f('ix_statistics_timeTaken'), 'statistics', ['timeTaken'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statistics_timeTaken'), table_name='statistics')
    op.drop_index(op.f('ix_statistics_score'), table_name='statistics')
    op.drop_table('statistics')
    # ### end Alembic commands ###
